2021/03/27 09:24:54 : Error Connecting:HTTPConnectionPool(host='127.0.1.1', port=8080): Max retries exceeded with url: /api/v1/action/setup_cart (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a090b6cd0>: Failed to establish a new connection: [Errno 111] Connection refused')) : False
